### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by GasperPaul** [pobiedimska/hangman#1]
In general, this is very good. 

https://github.com/pobiedimska/hangman/blob/5e11edba773b8e8eb7bac7338758b480cb1a957d/hangman.py#L87
https://github.com/pobiedimska/hangman/blob/5e11edba773b8e8eb7bac7338758b480cb1a957d/hangman.py#L98
https://github.com/pobiedimska/hangman/blob/5e11edba773b8e8eb7bac7338758b480cb1a957d/hangman.py#L169

Loops inside this functions can be re-written as a `map` or a generator.

https://github.com/pobiedimska/hangman/blob/5e11edba773b8e8eb7bac7338758b480cb1a957d/hangman.py#L57
https://github.com/pobiedimska/hangman/blob/5e11edba773b8e8eb7bac7338758b480cb1a957d/hangman.py#L59

![That just sounds like `while True` with extra steps](https://i.imgflip.com/3iwt77.jpg)

https://github.com/pobiedimska/hangman/blob/5e11edba773b8e8eb7bac7338758b480cb1a957d/hangman.py#L60

You can add a parameter so that you know if this is a version with or without hints and process this accordingly.

https://github.com/pobiedimska/hangman/blob/5e11edba773b8e8eb7bac7338758b480cb1a957d/hangman.py#L63

This has no effect on the `warnings_remaining` outside the function. So, it's useless, basically.

https://github.com/pobiedimska/hangman/blob/5e11edba773b8e8eb7bac7338758b480cb1a957d/hangman.py#L71-L72

In general, it is a bad form to write like this. You should probably restate your `if` condition or code you wish to skip later in the loop. For example, you can use `must_continue` as an indicator, if you have it.

https://github.com/pobiedimska/hangman/blob/5e11edba773b8e8eb7bac7338758b480cb1a957d/hangman.py#L127-L128

If `warnings_remaining` is 0 you should not end the game, but decrease the number of guesses, see 2.D.2b.

https://github.com/pobiedimska/hangman/blob/5e11edba773b8e8eb7bac7338758b480cb1a957d/hangman.py#L140-L141

This should be considered an error due to the specification.

https://github.com/pobiedimska/hangman/blob/5e11edba773b8e8eb7bac7338758b480cb1a957d/hangman.py#L151

This is not the right way to calculate win score. You should count only unique letters. For example, word `apple` has 4 unique letters.

**Comment by pobiedimska** [comment]
Thank you! I've considered all admonitions and commited changes.

**Comment by GasperPaul** [comment]
Good job! I think you may close this.
